# Generated by Django 4.2.5 on 2023-10-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=255)),
                ("img", models.CharField(max_length=80)),
                ("status", models.IntegerField()),
            ],
            options={"db_table": "actions", "managed": False,},
        ),
        migrations.CreateModel(
            name="Applications",
            fields=[
                (
                    "application_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("formed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "applications", "managed": False,},
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={"db_table": "django_migrations", "managed": False,},
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("login", models.CharField(blank=True, max_length=20, null=True)),
                ("password", models.CharField(blank=True, max_length=20, null=True)),
                ("is_moderator", models.BooleanField(blank=True, null=True)),
                (
                    "fio",
                    models.CharField(
                        blank=True, db_column="FIO", max_length=75, null=True
                    ),
                ),
            ],
            options={"db_table": "users", "managed": False,},
        ),
        migrations.CreateModel(
            name="Applicationsactions",
            fields=[
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="voice_assistants_app.applications",
                    ),
                ),
                ("action", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.CharField(max_length=100)),
            ],
            options={"db_table": "applicationsactions", "managed": False,},
        ),
    ]
