# Generated by Django 4.2.5 on 2023-10-18 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actions",
            fields=[
                ("action_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=255)),
                ("img", models.CharField(max_length=80)),
                ("status", models.IntegerField()),
            ],
            options={"db_table": "actions",},
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("login", models.CharField(blank=True, max_length=20, null=True)),
                ("password", models.CharField(blank=True, max_length=20, null=True)),
                ("is_moderator", models.BooleanField(blank=True, null=True)),
                (
                    "fio",
                    models.CharField(
                        blank=True, db_column="FIO", max_length=75, null=True
                    ),
                ),
            ],
            options={"db_table": "users",},
        ),
        migrations.CreateModel(
            name="Applications",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("formed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="voice_assistants_app.users",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="applications_moderator_set",
                        to="voice_assistants_app.users",
                    ),
                ),
            ],
            options={"db_table": "applications",},
        ),
        migrations.CreateModel(
            name="ApplicationsActions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_action", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.CharField(max_length=100)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="voice_assistants_app.actions",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="voice_assistants_app.applications",
                    ),
                ),
            ],
            options={
                "db_table": "applications_actions",
                "unique_together": {("application", "action")},
            },
        ),
    ]
