# Generated by Django 4.2.5 on 2023-10-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_assistants_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actions",
            name="img",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
