# Generated by Django 4.2.5 on 2023-12-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("voice_assistants_app", "0002_alter_actions_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewUser",
            fields=[
                (
                    "users_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="voice_assistants_app.users",
                    ),
                ),
            ],
            bases=("voice_assistants_app.users",),
        ),
    ]
