# Generated by Django 4.2.5 on 2023-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("voice_assistants_app", "0003_newuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="newUser_groups",
            field=models.ManyToManyField(
                related_name="custom_newuser_groups", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="newuser",
            name="newUser_permissions",
            field=models.ManyToManyField(
                related_name="custom_newuser_permissions", to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="groups",
            field=models.ManyToManyField(
                related_name="custom_user_groups", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="custom_user_permissions", to="auth.permission"
            ),
        ),
    ]
