# Generated by Django 4.2.5 on 2023-12-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "voice_assistants_app",
            "0004_newuser_newuser_groups_newuser_newuser_permissions_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(name="NewUser",),
    ]
