# Generated by Django 4.2.5 on 2023-12-02 15:37

from django.db import migrations
import voice_assistants_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_assistants_app", "0005_delete_newuser"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[("objects", voice_assistants_app.models.NewUser()),],
        ),
    ]
