# Generated by Django 4.2.5 on 2023-12-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_assistants_app", "0006_alter_users_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="login",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
