# Generated by Django 4.2.5 on 2023-12-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_assistants_app", "0007_alter_users_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
