# Generated by Django 4.2.5 on 2023-12-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice_assistants_app", "0008_alter_users_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="fio",
            field=models.CharField(
                blank=True, db_column="FIO", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="login",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
