# Generated by Django 4.2.5 on 2023-10-13 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=255)),
                ("img", models.CharField(max_length=80)),
                ("status", models.IntegerField(default=0)),
            ],
            options={"db_table": "actions", "managed": True,},
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("login", models.CharField(blank=True, max_length=20, null=True)),
                ("password", models.CharField(blank=True, max_length=20, null=True)),
                ("is_moderator", models.BooleanField(blank=True, null=True)),
                ("FIO", models.CharField(blank=True, max_length=75, null=True)),
            ],
            options={
                "verbose_name_plural": "Users",
                "db_table": "users",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Applications",
            fields=[
                (
                    "application_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("formed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="applications_customer_set",
                        to="voice_helper.users",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="voice_helper.users",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Applications",
                "db_table": "applications",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ApplicationsActions",
            fields=[
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="voice_helper.applications",
                    ),
                ),
                ("action", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(max_length=100)),
                (
                    "action_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="voice_helper.actions",
                    ),
                ),
            ],
            options={
                "db_table": "applicationsactions",
                "managed": True,
                "unique_together": {("application", "action_id")},
            },
        ),
    ]
