# Generated by Django 4.2.5 on 2024-01-07 21:13

from django.db import migrations, models
import voice_assistants_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actions",
            fields=[
                ("action_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=255)),
                ("img", models.CharField(max_length=255)),
                ("status", models.IntegerField()),
            ],
            options={"db_table": "actions", "managed": False,},
        ),
        migrations.CreateModel(
            name="Applications",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("formed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "applications", "managed": False,},
        ),
        migrations.CreateModel(
            name="ApplicationsActions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_action", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.CharField(max_length=100)),
            ],
            options={"db_table": "applications_actions", "managed": False,},
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "login",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("is_moderator", models.BooleanField(blank=True, null=True)),
                (
                    "fio",
                    models.CharField(
                        blank=True, db_column="FIO", max_length=255, null=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="custom_user_groups", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        related_name="custom_user_permissions", to="auth.permission"
                    ),
                ),
            ],
            options={"db_table": "users",},
            managers=[("objects", voice_assistants_app.models.NewUser()),],
        ),
    ]
